spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

server:
  error:
    include-message: never
    include-stacktrace: never

logging:
  level:
    com.company.project: WARN
    org.springframework.security: WARN
